# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-01 23:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admincatsanddogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cats',
            name='ownerid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dogs',
            name='ownerid',
            field=models.IntegerField(default=0),
        ),
    ]
